baseURL = "https://lasout-dev.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Nicolas Kohout"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Nicolas Kohout"
author = "Nicolas Kohout"
description = "The personal homepage of Nicolas Kohout"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/nicolas-kohout-94212120/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Lasout"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@lasout.io"

## Menu items
      [menu]

  [[menu.main]]
  name = "NK"
  weight = 100
  identifier = "about"
  url = "/"

  [[menu.main]]
  name = "My CV"
  weight = 200
  identifier = "CV"
  url = "/cv/"
